### ISSUE TITLE
Auto Start Navigation

### ISSUE THREAD

**Issue by Bryze** [tiaanduplessis/react-native-google-maps-directions#13]
I have a requirement that on loading the google map application, have to automatically start the navigation.

Current scenario - It shows the route but user has to click on `start` to start navigation
I couldn't find any flag associated for the same?

Any idea how could we approach the problem?

**Comment by adaltavo** [comment]
It's already fixed. You must use the parameter `dir_action=navigate`. An example was added in README

**Comment by web75018** [comment]
Hi @adaltavo 
i'm looking for a react native navigation solution.
can you share any link or plugin ?
Thanks
