### ISSUE TITLE
Duplicate code

### ISSUE THREAD

**Issue by nwaughachukwuma** [tiaanduplessis/react-native-google-maps-directions#25]
Hi @tiaanduplessis is see there's a duplicate code in the index file (see attachment). I needed to know what its use is, and if it's an oversight, I am able to do a PR to fix it.

<img width="582" alt="Screenshot 2019-10-03 at 04 48 10" src="https://user-images.githubusercontent.com/20521315/66098224-aefbb800-e599-11e9-8800-d7daf7ecc1d7.png">

**Comment by tiaanduplessis** [comment]
Hi @nwaughachukwuma, thanks for the catch. It must have been a merge issue. I'll fix it

**Comment by tiaanduplessis** [comment]
Removed in `v2.1.1`
