### ISSUE TITLE
Issue with displaying Dropped Pins on iOS13

### ISSUE THREAD

**Issue by RixBai** [tiaanduplessis/react-native-google-maps-directions#26]
I have an issue with displaying Dropped Pins on iOS13.
![2E1792FA-4DF1-4AF1-811A-E79EB334651B](https://user-images.githubusercontent.com/43899212/69067512-09c96180-09d8-11ea-8239-7d6ce10f9637.jpg)

**Comment by RixBai** [comment]
Closing  the issue because of no response.

**Comment by RameshDev92** [comment]
Hi  @RixBai 
I am also having the same issue.Did you find any solution.
Thank you.
