### ISSUE TITLE
Support for multiple waypoints and optimizeWayPoints

### ISSUE THREAD

**Issue by tugrulcan** [tiaanduplessis/react-native-google-maps-directions#4]
Hi,
Firstly thank you for this great package.
Is it possible for you to add support for multiple waypoints and optimize option?

**Comment by tiaanduplessis** [comment]
Hi. I'm quite busy at the moment, but will look into implementing it as soon as I have time 👍

**Comment by tugrulcan** [comment]
I've implemented my version using yours. It generates the following url: `https://l.facebook.com/l.php?u=http%3A%2F%2Fmaps.google.com%2Fmaps%3Fsaddr%3D38.43882333333333%252C27.202935000000004%26daddr%3D1901.%2520Sk.%2520No%253A43%252C%2520Saruhan%2520Mahallesi%252C%252045010%2520Manisa%2520Merkez%252FManisa%252C%2520T%25C3%25BCrkiye%2520to%253AOktay%2520Erol%2520Pulcuo%25C4%259Flu%2520Cd.%2520No%253A8%252C%252045030%2520Ke%25C3%25A7ilik%25C3%25B6y%2520Osb%252FManisa%2520Merkez%252FManisa%252C%2520T%25C3%25BCrkiye%2520to%253AManisa%2520TOK%25C4%25B0%2520Konutlar%25C4%25B1%2520No%253A3%252C%2520Uncubozk%25C3%25B6y%2520Mahallesi%252C%252045030%2520Manisa%2520Merkez%252FManisa%252C%2520T%25C3%25BCrkiye%2520to%253A5619.%2520Sk.%2520No%253A2%252C%2520Ke%25C3%25A7ili%2520K%25C3%25B6y%2520Mahallesi%252C%252045030%2520Manisa%2520Merkez%252FManisa%252C%2520T%25C3%25BCrkiye%2520to%253AVali%2520Azizbey%2520Cd.%2520No%253A34%252C%252075.%2520Y%25C4%25B1l%2520Mahallesi%252C%252045030%2520Manisa%2520Merkez%252FManisa%252C%2520T%25C3%25BCrkiye%2520to%253A43.%2520Sk.%2520No%253A23%252C%2520Turgut%2520%25C3%2596zal%2520Mahallesi%252C%252045040%2520Manisa%2520Merkez%252FManisa%252C%2520T%25C3%25BCrkiye%2520to%253A308.%2520Sk.%2520No%253A130%252C%2520Kaz%25C4%25B1m%2520Karabekir%2520Mahallesi%252C%252045040%2520%25C5%259Eehzadeler%252FManisa%252C%2520T%25C3%25BCrkiye%2520to%253A1803.%2520Sk.%2520No%253A7%252C%2520%25C3%2587ar%25C5%259F%25C4%25B1%2520Mahallesi%252C%252045010%2520Manisa%2520Merkez%252FManisa%252C%2520T%25C3%25BCrkiye%2520to%253AMuradiye%2520Mah.%2520Manolya%2520Sokak%2520No%253A234%2520Yunusemre%2520-%2520Manisa%26dirflg%3Dd&h=ATNxQD42u56k8kvAINvUeEVAassW-0_mA1r5ZjDcR5urwdLjPPNnc6f5im6_QAEyMY7xLg9uj2o9vzCiu33CClYh-MRlsGLykJo06WUto21ZL5ftGFLzUv91DHpy8FZiTnKoeoRcObmKzw`
This generated url works on web browsers. But my problem occurs when I pass this url to Linking method. 
`Linking.openURL(url);`
Google maps application does not opens the link as in browsers.

**Comment by tiaanduplessis** [comment]
@donovantc any thoughts?

**Comment by donovantc** [comment]
Hey @tugrulcan,

is this the url that gets generated by this package?

When I try this url in the browser, it cannot find one of the points but I don't think that is the issue.

Could you share the data that you pass as a parameter to `getDirections(data)`?

**Comment by Aboukinane** [comment]
@tugrulcan  i have made a PR now it supports waypoints  , awaiting approval ...

**Comment by tiaanduplessis** [comment]
In 2.1.0
