### ISSUE TITLE
Allow for empty source

### ISSUE THREAD

**Issue by kytwb** [tiaanduplessis/react-native-google-maps-directions#5]
Would it be feasible to allow for empty source so Google Maps opens with the destination pre-filled and let the user specify the source directly in Google Maps?

**Comment by benhannel** [comment]
I added support for this in my fork https://github.com/tiaanduplessis/react-native-google-maps-directions/pull/7

**Comment by tiaanduplessis** [comment]
Added with the latest release 🎉
