### ISSUE TITLE
It does not take dynamic data from api

### ISSUE THREAD

**Issue by anjali14garg** [tiaanduplessis/react-native-google-maps-directions#6]
handleGetDirections = () => {
       const data = {
             source: {
              latitude: 19.295296,
              longitude: -81.382111
            },
            destination: {
              latitude:this.props.customer.latitude,
              longitude: this.props.customer.longitude
            },
            params: [
              {
                key: "dirflg",
                value: "w"
              }
            ]
          }
          getDirections(data)
        }
it is showing the error of  Possible Unhandled Promise Rejection (id: 0):
Error: Invalid arguments provided

**Comment by tiaanduplessis** [comment]
@anjali14garg please check if the issue still persists with v1.1.2

**Comment by tiaanduplessis** [comment]
Closing this issue in the meantime. If you still encounter the bug, please feel free to reopen the issue 👍
